"""replace_commute_departure_time_with_jsonb_array

Revision ID: 188a30d8e27e
Revises: 1cd9c2831ad0
Create Date: 2026-04-04 10:58:00.906486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '188a30d8e27e'
down_revision: Union[str, Sequence[str], None] = '1cd9c2831ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('commute_departure_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('users', 'commute_departure_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('commute_departure_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('users', 'commute_departure_times')
    # ### end Alembic commands ###
